## Travis CI Configuration file

# Use barebones Travis image
language: c

# Only grab latest git commit (no need for history)
git:
  depth: 1
  submodules: true

# Cache the compilers folder so we don't have to download and unpack it for every build
cache:
  directories:
    - $HOME/compilers/

# Download and unpack the latest GNU ARM Embedded Toolchain if it's not already there
#  Also add the gcc/bin folder to $PATH
install:
  - export GCC_DIR=$HOME/compilers/gcc-arm-none-eabi-7-2017-q4-major
  - export GCC_ARCHIVE=$HOME/gcc-arm-none-eabi-7-2017-q4-major-linux.tar.bz2
  - export GCC_URL=https://developer.arm.com/-/media/Files/downloads/gnu-rm/7-2017q4/gcc-arm-none-eabi-7-2017-q4-major-linux.tar.bz2
  - if [ ! -e $GCC_DIR/bin/arm-none-eabi-gcc ]; then wget -nv $GCC_URL -O $GCC_ARCHIVE; tar xfj $GCC_ARCHIVE -C $HOME/compilers; fi
  - export PATH=$PATH:$GCC_DIR/bin

# List of tests to run ( `./build PAYLOAD` )
env:
  - PAYLOAD=1900
  - PAYLOAD=1901

# Command to run tests
script: cd firmware-tracker-phil/ && ./build $PAYLOAD