#!/usr/bin/env bash

gnss_constellations="gps,glo"
gnss_datatype="alm,pos"
gnss_data_maxage=$((3*3600))

# Dartmoor
gnss_pos_latitude="50.6628"
gnss_pos_longitude="-4.1816"
gnss_pos_radius="400000" # 400km